// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/catalog/catalog.proto

package com_deliveryapp_service_catalog

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Catalog service

func NewCatalogEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Catalog service

type CatalogService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Catalog_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Catalog_PingPongService, error)
}

type catalogService struct {
	c    client.Client
	name string
}

func NewCatalogService(name string, c client.Client) CatalogService {
	return &catalogService{
		c:    c,
		name: name,
	}
}

func (c *catalogService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Catalog.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Catalog_StreamService, error) {
	req := c.c.NewRequest(c.name, "Catalog.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &catalogServiceStream{stream}, nil
}

type Catalog_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type catalogServiceStream struct {
	stream client.Stream
}

func (x *catalogServiceStream) Close() error {
	return x.stream.Close()
}

func (x *catalogServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *catalogServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *catalogServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *catalogServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *catalogService) PingPong(ctx context.Context, opts ...client.CallOption) (Catalog_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Catalog.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &catalogServicePingPong{stream}, nil
}

type Catalog_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type catalogServicePingPong struct {
	stream client.Stream
}

func (x *catalogServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *catalogServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *catalogServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *catalogServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *catalogServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *catalogServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Catalog service

type CatalogHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Catalog_StreamStream) error
	PingPong(context.Context, Catalog_PingPongStream) error
}

func RegisterCatalogHandler(s server.Server, hdlr CatalogHandler, opts ...server.HandlerOption) error {
	type catalog interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Catalog struct {
		catalog
	}
	h := &catalogHandler{hdlr}
	return s.Handle(s.NewHandler(&Catalog{h}, opts...))
}

type catalogHandler struct {
	CatalogHandler
}

func (h *catalogHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.CatalogHandler.Call(ctx, in, out)
}

func (h *catalogHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.CatalogHandler.Stream(ctx, m, &catalogStreamStream{stream})
}

type Catalog_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type catalogStreamStream struct {
	stream server.Stream
}

func (x *catalogStreamStream) Close() error {
	return x.stream.Close()
}

func (x *catalogStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *catalogStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *catalogStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *catalogStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *catalogHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.CatalogHandler.PingPong(ctx, &catalogPingPongStream{stream})
}

type Catalog_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type catalogPingPongStream struct {
	stream server.Stream
}

func (x *catalogPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *catalogPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *catalogPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *catalogPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *catalogPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *catalogPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
